package com.jlee.leetcodesolutions;

import java.util.ArrayList;

public class LeetCode389 {
  /*
   * Given two strings s and t which consist of only lowercase letters.
   * 
   * String t is generated by random shuffling string s and then add one more
   * letter at a random position.
   * 
   * Find the letter that was added in t.
   * 
   * https://leetcode.com/problems/find-the-difference/description/
   */
  public char findTheDifference(String s, String t) {
    if(s == null || t == null)
      return '0';
    
    // Store all chars of s-string into List
    ArrayList<Character> inputList = new ArrayList<Character>();
    for(int i = 0; i < s.length(); i++)
      inputList.add((Character)s.charAt(i));
    
    // Check t-string against List.  Remove if found
    for(int i = 0; i < t.length(); i++) {
      if(inputList.contains((Character)t.charAt(i)))
        inputList.remove((Character)t.charAt(i));
      else
        return t.charAt(i);
    }
    return '0';
  }
}
