package com.jlee.leetcodesolutions;

public class LeetCode0389 {
  /*
   * Given two strings s and t which consist of only lowercase letters.
   * 
   * String t is generated by random shuffling string s and then add one more
   * letter at a random position.
   * 
   * Find the letter that was added in t.
   * 
   * https://leetcode.com/problems/find-the-difference/description/
   */
  public char findTheDifference(String s, String t) {
    int[] count = new int[26];
    for(int i = 0; i < s.length() || i < t.length(); i++) {
      if(i < s.length())
        count[s.charAt(i) - 'a']++;
      
      if(i < t.length())
        count[t.charAt(i) - 'a']--;
    }
    
    // find char with count == -1
    for(int i = 0; i < 26; i++) {
      if(count[i] == -1)
        return (char) (i + 'a');
    }
    return 0;
  }
}
